stages:
  load_data:
    cmd: python stage1_load_save.py --config=configuration/config.yaml
    deps:
      - stage1_load_save.py
      - src/utils/all_utils.py
      - configuration/config.yaml
    outs:
      - artifacts/local_dir/data.csv
  split_data:
    cmd: python stage2_split_data.py --config=configuration/config.yaml --params=params.yaml
    deps:
      - stage2_split_data.py
      - src/utils/all_utils.py
      - configuration/config.yaml
      - params.yaml
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv

  always_run:
    cmd: python stage1_load_save.py --config=configuration/config.yaml
