data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv

artifacts:
  artifcats_dir: artifacts
  raw_local_dir: local_dir
  raw_local_file: data.csv

  split_data_dir: split_data_dir
  train: train.csv
  test: test.csv

  model_save_path: models
  model_name: Elastic_Model.sav

  reports_dir : reports
  scores : scores.json

